version: "2.0"
services:
  web: 
    build: .
    volumes: 
     - .:/var/www/html
    expose:
      - "8000"
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - SERVERNAME=naspi.local
      - SERVERALIAS=naspi.local *.alliance.local
    links:
     - db
     - redis
  db:
    image: mysql:5.7
    ports:
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alliance
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
  redis:
    image: "redis:alpine"
  phpredisadmin:
    image: actency/docker-phpredisadmin
    ports:
      - "9900:80"
    environment:
      - REDIS_1_HOST=redis
    links:
      - redis